name: CI/CD for Order-Service (via Helm + ArgoCD)

on:
  push:
    branches:
      - dev

env:
  SERVICE_NAME: order-service

  INFRA_REPO: leninkart-infra
  INFRA_BRANCH: dev

  VALUES_FILE: helm/order-service/values-dev.yaml

  SECRET_INFRA_PAT: INFRA_PAT

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.export.outputs.image_tag }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_TAG="${{ github.run_id }}"
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${IMAGE_TAG}"

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t "$IMAGE" .

      - name: Push Docker Image
        run: docker push "$IMAGE"

      - name: Export Image Tag
        id: export
        run: |
          echo "image_tag=${{ github.run_id }}" >> $GITHUB_OUTPUT

  update-helm-values:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Infra Repo (dev)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ env.INFRA_REPO }}
          token: ${{ secrets[env.SECRET_INFRA_PAT] }}
          ref: ${{ env.INFRA_BRANCH }}

      - name: Update order-service Helm values
        run: |
          IMAGE_REPO="${{ secrets.DOCKERHUB_USERNAME }}/order-service"
          IMAGE_TAG="${{ needs.build.outputs.image_tag }}"

          sed -i "s|repository:.*|repository: $IMAGE_REPO|" ${{ env.VALUES_FILE }}
          sed -i "s|tag:.*|tag: \"$IMAGE_TAG\"|" ${{ env.VALUES_FILE }}

          echo "Updated file:"
          cat ${{ env.VALUES_FILE }}

      - name: Commit & Push (dev)
        run: |
          git config --global user.email "Leninfitfreak@gmail.com"
          git config --global user.name "Leningithubactions"

          git add ${{ env.VALUES_FILE }}
          git commit -m "Update image for order-service -> run-${{ needs.build.outputs.image_tag }}" || echo "No changes"
          git push origin dev
